first commit

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -1,7 +1,7 @@
 name: 09 - Using functions
 
 on:
-  pull_request:
+  #pull_request:
   workflow_dispatch:
 
 jobs:
@@ -17,10 +17,10 @@ jobs:
       - name: Bug Step
         if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
         run: echo "I am bug fix"
-      - name: Sleep for 20 seconds
-        run: sleep 20
-      - name: Failing Step
-        run: exit 1
+      #- name: Sleep for 20 seconds
+      #  run: sleep 20
+      #- name: Failing Step
+      #  run: exit 1
       - name: I will be skipped
         if: ${{ success() }}
         run: echo "I will print if previous step succeed"
